version: "3"

services:
  db:
    container_name: todo-app-db
    image: postgres:14.2
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 3307:3306
    networks:
      app_net:
        ipv4_address: "172.10.0.2"

  # bundle exec rails s -p 4000 -b '0.0.0.0'
  backend:
    container_name: todo-app-backend
    build: .
    image: todo-app-backend
    command: |
      bash -c "bundle install -j4
      rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    # bundle exec puma -C config/puma.rb"
    tty: true
    stdin_open: true
    volumes:
      - ./:/app:cached
      - bundle_data:/usr/local/bundle:cached
      - public_data:/app/public
      - tmp_data:/app/tmp
      - log_data:/app/log
      - /app/vendor
      - /app/.git
    environment:
      - TZ=Asia/Tokyo
      - TODO_APP_API_HOST=http://localhost:4000
      - TODO_APP_FRONT_HOST=http://localhost:3000
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
    ports:
      - 4000:4000
    networks:
      app_net:
        ipv4_address: "172.10.0.3"

  # 参考: https://toranoana-lab.hatenablog.com/entry/2020/08/14/175706
  #nginx:
  #  build:
  #    context: ./nginx/
  #  volumes:
  #    - public_data:/app/public
  #    - tmp_data:/app/tmp
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - backend
  #    - db
  #  networks:
  #    app_net:
  #      ipv4_address: "172.10.0.4"

  frontend:
    container_name: todo-app-frontend
    build: ./frontend/
    image: todo-app-frontend
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - TODO_APP_API_HOST=http://localhost:80
      - TODO_APP_FRONT_HOST=http://localhost:3000
    volumes:
      - ./frontend:/app:cached
    ports:
      - 3000:3000
    command: "yarn run dev"
    networks:
      app_net:
        ipv4_address: "172.10.0.5"
    depends_on:
      - backend
      - db
 
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24

volumes:
  postgres_data:
  bundle_data:
  public_data:
  tmp_data:
  log_data:
